language: node_js
node_js:
  - "10"

script: echo "Running tests against $(node -v) ..."

jobs:
  include:
    - stage: test
      script: npm run test
    - stage: npm release
      node_js: "10"
      script: echo "Deploying to npm ..."
      deploy:
        provider: npm
        email: "sun1993hlj@hotmail.com"
        api_key: $NODE_TOKEN
        skip_cleanup: true
cache:
  directories:
    - "node_modules"